cities:
  Seoul:
    allowed_horizons:
      - market_open
      - previous_evening
      - morning_of
  NYC:
    allowed_horizons:
      - market_open
      - previous_evening
  London:
    allowed_horizons:
      - market_open
      - previous_evening
      - morning_of
